services:
  elliot:
    image: valentinschabschneider/elliot:0.6.1
    environment:
      MAX_TIMEOUT: ${MAX_TIMEOUT}
      PERSIST_PERIOD: ${PERSIST_PERIOD}
      QUEUE_CONCURRENCY: ${QUEUE_CONCURRENCY}
      ADDITIONAL_SCRIPTS: ${ADDITIONAL_SCRIPTS}
      API_KEY: ${API_KEY}
      REDIS_URL: redis://redis:6379
      BROWSERLESS_ENDPOINT: ws://browserless:3000/chromium?token=${BROWSERLESS_TOKEN}
      BULL_BOARD_PASSWORD: ${BULL_BOARD_PASSWORD}
    ports:
      - 3000:3000
    depends_on:
      - redis
      - browserless
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

  browserless:
    image: ghcr.io/browserless/chromium:v2.31.0
    environment:
      MAX_CONCURRENT_SESSIONS: 10
      CONNECTION_TIMEOUT: 60000
      MAX_QUEUE_LENGTH: 20
      PREBOOT_CHROME: true
      DEMO_MODE: false
      ENABLE_DEBUGGER: false
      WORKSPACE_DELETE_EXPIRED: true
      TOKEN: ${BROWSERLESS_TOKEN}
    restart: unless-stopped

volumes:
  redis-data:
