onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - core-js
  - es5-ext
  - msgpackr-extract
  - postinstall-postinstall
  - puppeteer
patchedDependencies:
  pagedjs-cli@0.4.3: patches/pagedjs-cli@0.4.3.patch
