version: '3'
services:
  elliot:
    build:
      target: base
      args:
        NODE_BASE_IMAGE: node:19
    environment:
      CHOKIDAR_USEPOLLING: true
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
